// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package project.domain;

import org.springframework.beans.factory.annotation.Configurable;
import project.domain.CustomerIntegrationTest;

privileged aspect CustomerIntegrationTest_Roo_Configurable {
    
    declare @type: CustomerIntegrationTest: @Configurable;
    
}
